; Skyrim Configuration File Example
; This is a sample INI file for testing the Skyrim INI Editor

[Display]
; horizontal resolution
; this should match your monitor
iSize W=1920
; vertical resolution
iSize H=1080
; fullscreen toggle
bFull Screen=true
bBorderless=true
iAdapter=0
iVSyncPresentInterval=1

[General]
sLanguage=ENGLISH
fBrightLightColorB=1.0000
fBrightLightColorG=1.0000
fBrightLightColorR=1.0000
iStoryManagerLoggingEvent=-1
bEnableStoryManagerLogging=false

[GamePlay]
bShowFloatingQuestMarkers=true
bShowQuestMarkers=true
iDifficulty=2
bShowCompass=true

[Interface]
bDialogueSubtitles=true
bGeneralSubtitles=true
fMouseCursorSpeed=1.0000
bShowCrosshair=true

[Controls]
fGamepadHeadingSensitivity=1.0000
fMouseHeadingSensitivity=0.0125
bGamePadRumble=true
bMouseAcceleration=true

[Particles]
iMaxDesired=750

[SaveGame]
fAutosaveEveryXMinutes=10.0000

[AudioMenu]
fAudioMasterVolume=1.0000
fVal7=1.0000
fVal6=1.0000
fVal5=0.6000
fVal4=1.0000
fVal3=0.3000
fVal2=1.0000
fVal1=1.0000
fVal0=0.8000

[Grass]
bAllowCreateGrass=true
bAllowLoadGrass=false
fGrassMaxStartFadeDistance=7000.0000
fGrassMinStartFadeDistance=0.0000

[Water]
bReflectExplosions=false
